---
name: Test CI
on:
  push:
    branches:
      - main
      - CI-Testing
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo ./setup-mongocxx
        sudo apt-get install libboost-all-dev libcurl4-openssl-dev libssl-dev nlohmann-json3-dev
        sudo apt-get install libpoppler-dev poppler-utils
        sudo apt-get install -y libpoppler-cpp-dev
        sudo apt-get install tesseract-ocr libtesseract-dev g++ autoconf automake libtool pkg-config libpng-dev libjpeg8-dev libtiff5-dev zlib1g-dev libwebpdemux2 libwebp-dev libopenjp2-7-dev libgif-dev libarchive-dev libcurl4-openssl-dev libleptonica-dev libpoppler-dev libglib2.0-dev poppler-utils nlohmann-json3-dev
        mkdir tessdata && export TESSDATA_PREFIX=$(pwd)/tessdata/ && wget --recursive --no-parent https://github.com/tesseract-ocr/tessdata_fast.git $(pwd)/tessdata/
    - name: Run tests
      run: |
        cd test
        sudo ./installGtest.sh
        ./runGtest.sh
